# SPDX-FileCopyrightText: 2025 Alexandre Gomes Gaigalas <alganet@gmail.com>
# SPDX-License-Identifier: ISC

name: Push alganet/shell-versions:all

permissions:
  contents: read

on:
  push:
    branches:
      - "main"
jobs:
  download:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/downloads
  build:
    needs: download
    runs-on: ubuntu-24.04

    continue-on-error: ${{ matrix.can_fail_build }}
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/downloads

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ matrix.tags }}
          labels: ${{ matrix.name }}
          build-args: |
            TARGETS=${{ matrix.targets }}

      - name: Generate and upload build checksums
        uses: ./.github/actions/generate-build-checksums
        with:
          image: ${{ matrix.tags }}
          artifact_name: shvr-build-checksums

    strategy:
      fail-fast: true
      matrix:
        include:
          - name: all
            can_fail_build: false
            tags: alganet/shell-versions:all
            # AUTO-GENERATED LIST. DO NOT EDIT MANUALLY.
            targets: >
              ash_1.37.0
              ash_1.36.1
              ash_1.35.0
              ash_1.34.1
              ash_1.33.2
              ash_1.32.1
              ash_1.31.1
              ash_1.30.1
              ash_1.29.3
              ash_1.28.4
              ash_1.27.2
              ash_1.26.2
              ash_1.25.1
              bash_5.3.9
              bash_5.2.37
              bash_5.1.16
              bash_5.0.18
              bash_4.4.23
              bash_4.3.48
              bash_4.2.53
              bash_4.1.17
              bash_4.0.44
              bash_3.2.57
              bash_3.1.23
              bash_3.0.22
              bash_2.05b.13
              brush_0.3.0
              brush_0.2.23
              dash_0.5.13
              dash_0.5.12
              dash_0.5.11.5
              dash_0.5.10.2
              dash_0.5.9.1
              dash_0.5.8
              dash_0.5.7
              dash_0.5.6.1
              dash_0.5.5.1
              hush_1.37.0
              hush_1.36.1
              hush_1.35.0
              hush_1.34.1
              hush_1.33.2
              hush_1.32.1
              hush_1.31.1
              hush_1.30.1
              hush_1.29.3
              hush_1.28.4
              hush_1.27.2
              hush_1.26.2
              hush_1.25.1
              ksh_shvrChistory-b_2016-01-10
              ksh_shvrChistory-b_2012-08-01
              ksh_shvrChistory-b_2011-03-10
              ksh_shvrChistory-b_2010-10-26
              ksh_shvrChistory-b_2010-06-21
              ksh_shvrChistory-b_2008-11-04
              ksh_shvrChistory-b_2008-06-08
              ksh_shvrChistory-b_2008-02-02
              ksh_shvrChistory-b_2007-01-11
              ksh_shvrB2020-2020.0.0
              ksh_shvrA93uplusm-v1.0.10
              ksh_shvrA93uplusm-v1.0.9
              ksh_shvrA93uplusm-v1.0.8
              ksh_shvrA93uplusm-v1.0.7
              ksh_shvrA93uplusm-v1.0.6
              ksh_shvrA93uplusm-v1.0.4
              ksh_shvrA93uplusm-v1.0.3
              ksh_shvrA93uplusm-v1.0.2
              ksh_shvrA93uplusm-v1.0.1
              loksh_7.8
              loksh_7.7
              loksh_7.6
              loksh_7.5
              loksh_7.4
              loksh_7.3
              loksh_7.1
              loksh_7.0
              loksh_6.9
              loksh_6.8.1
              loksh_6.7.5
              mksh_R59c
              mksh_R58
              mksh_R57
              mksh_R56c
              mksh_R55
              mksh_R54
              mksh_R53a
              mksh_R52c
              mksh_R51
              mksh_R50f
              mksh_R49
              mksh_R48b
              mksh_R47
              mksh_R46
              mksh_R45
              oksh_7.8
              oksh_7.7
              oksh_7.6
              oksh_7.5
              oksh_7.4
              oksh_7.3
              oksh_7.2
              oksh_7.1
              oksh_7.0
              oksh_6.9
              oksh_6.8.1
              oksh_6.7.1
              oksh_6.6
              oksh_6.5
              osh_0.37.0
              osh_0.36.0
              osh_0.35.0
              osh_0.34.0
              osh_0.33.0
              osh_0.32.0
              osh_0.31.0
              osh_0.30.0
              osh_0.29.0
              osh_0.28.0
              osh_0.27.0
              osh_0.26.0
              osh_0.25.0
              posh_0.14.3
              posh_0.13.2
              posh_0.12.6
              yash_2.60
              yash_2.59
              yash_2.58.1
              yash_2.57
              yash_2.56.1
              yash_2.55
              yash_2.54
              yash_2.53
              yash_2.52
              yash_2.51
              yash_2.50
              yash_2.49
              yash_2.48
              yash_2.47
              yash_2.46
              yash_2.45
              yash_2.44
              yash_2.43
              yash_2.42
              yash_2.41
              yashrs_3.0.4
              yashrs_0.4.5
              yashrs_0.4.0
              yashrs_0.3.0
              zsh_5.9
              zsh_5.8.1
              zsh_5.7.1
              zsh_5.6.2
              zsh_5.5.1
              zsh_5.4.2
              zsh_5.3.1
              zsh_5.2
              zsh_5.1.1
              zsh_5.0.8
              zsh_4.2.7
